sudo: true
language: java
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
      - docker-ce
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - chmod +x mvnw

script:
  - docker-compose up -d
after_script:
  - docker-compose down

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag payroll-api-tests $DOCKER_USER/payroll-api-tests:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/payroll-api-tests:$TRAVIS_BUILD_NUMBER
  - docker tag payroll-api-tests $DOCKER_USER/payroll-api-tests:latest
  - docker push $DOCKER_USER/payroll-api-tests:latest
