sudo: true
language: java
jdk: openjdk8
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose up

#after_script:
#  - docker-compose down