sudo: true
language: java
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
      - docker-ce
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

script:
  - docker-compose up

#after_script:
#  - docker-compose down