version: "3"
services:
  api-test:
    image: tad0ckerid/payroll-api-tests:1.0
    network_mode: host
    depends_on:
      - payroll
    # run the api tests
    environment:
      WAIT_HOSTS: payroll:80
    command: mvn clean install
  payroll:
    image: tad0ckerid/payroll-app:latest
    # bind the ports
    ports:
      - "80:80"
    # run the api
    command: mvn spring-boot:run